let string1 = "SLOW YOUR SHIT DOWN YOU BUNNY HOPPING ASS HAT! ARE YOU JUST TRYING TO RUN AWAY FROM RESPONSABILITY ? PLAY THE GAME THE WAY IT WAS INTENDED, YOU LOOSER!";
let string2 = "GORDON, YOU LOUSY MOTHERFUCKER, GET YOUR DORK ASS DOWN TO THE TEST CHAMBER OR ELSE ILL SHOVE THE SAMPLE UP YOUR ASS!";
let string3= "STOP FUCKING WITH THE MICROWAVE!";